export const STRINGS = {    
    BUTTON_BACK: 'Zurück',
    BUTTON_CANCEL: 'Abbrechen',
    BUTTON_LOGIN: 'Log in',   
    BUTTON_LOGOUT: 'Log out', 
    BUTTON_OK: 'Ok',
    BUTTON_SIGN_UP: 'Sign up',
    COMMENTS_ADD: 'Kommentar schreiben',
    COMMENTS_DELETE: 'löschen',
    COMMENTS_EDIT: 'editieren',
    COORDINATES_ERROR: 'Koordinaten aus den Parametern sind keine Zahlen!',
    DIALOG_ACCEPT: 'Ja',
    DIALOG_REJECT: 'Nein',
    ERROR_UNKNOWN: 'Ein unbekannter Fehler ist aufgetreten...',
    EMAIL_CONFIRM_TITLE: 'Bestätige deine E-Mail Adresse',
    EMAIL_CONFIRM_TEXT: 'Du hast eine Mail bekommen, folge dem Link, um deine E-Mail Adresse zu bestätigen!',
    EMAIL_CONFIRM_SUCCESS_TITLE: 'E-Mail Adresse bestätigt',
    EMAIL_CONFIRM_SUCCESS_TEXT: 'Du hast deine Email erfolgreich bestätigt! Klicke den nachfolgenden Link, um dich einzuloggen: ',
    EMAIL_CONFIRM_FAIL_TITLE: 'E-Mail Adresse konnte nicht verifiziert werden',
    EMAIL_CONFIRM_FAIL_TEXT: 'Leider konnte deine Email nicht verifiziert werden! Versuch es bitte erneut.',
    FAVORITES_ADD: 'Zu Favoriten hinzufügen',
    FAVORITES_REMOVE: 'Von Favoriten entfernen',
    FILTER_CLEAR: 'Filter löschen',
    IMAGES_EDIT: 'Bilder bearbeiten',
    IMAGES_DELETE: 'Willst du das Bild wirklich löschen?',
    IMAGES_NONE_UPLOADED: 'Du hast noch keine Bilder hochgeladen',
    IMAGES_MANAGE: 'Bilder verwalten',
    IMAGES_UPLOAD: 'Bilder hochladen',
    INPUT_COMMENT_LABEL: 'Kommentar',
    INPUT_COMMENT_ERROR: 'Gib bitte mindestens 3 Zeichen ein!',
    INPUT_CONFIRM_PASSWORD_LABEL: 'Passwort wiederholen',
    INPUT_CONFIRM_PASSWORD_ERROR: 'Die beiden Passwörter müssen übereinstimmen!',
    INPUT_EMAIL_LABEL: 'E-Mail',
    INPUT_EMAIL_ERROR: 'Gib bitte eine richtige E-Mail Adresse ein!',
    INPUT_NAME_LABEL: 'Name',
    INPUT_NAME_ERROR: 'Gib bitte zwischen 3 und 25 Zeichen ein!',
    INPUT_PASSWORD_LABEL: 'Passwort',
    INPUT_PASSWORD_ERROR: 'Das Passwort muss mindestens 10 Zeichen lang sein!',
    LOGIN_SUCCESS: 'Login erfolgreich',
    LOGIN_FAIL: 'Login fehlgeschlagen',
    PAGE_HOME: 'Home',
    PAGE_DETAILS: 'Details',
    PAGE_FAVORITES: 'Favoriten',
    PAGE_PROFILE: 'Profil',
    PAGE_NOT_FOUND_TEXT: 'Uuups... Wir konnten die gesuchte Seite nicht finden!',
    PAGE_NOT_FOUND_TITLE: 'Seite nicht gefunden!',
    PAGE_NOT_FOUND_LINK_TEXT: 'Hier kommst du zurück',
    PROFILE_RESET_PASSWORD: 'Passwort zurücksetzen',
    PROFILE_DELETE_ACCOUNT: 'Profil löschen',
    SEARCH_PLACEHOLDER: 'Suche nach Straßen, Plätzen ...',
    VENUE_RADIUS: 'Suchradius',
}