enum SPORT_TYPE {
    BASKETBALL = 'Basketball',
    FITNESS = 'Fitness',
    SOCCER = 'Fußball',
    TABLE_TENNIS = 'Tischtennis',
}

const ALLOWED_SPORT_TYPES = [SPORT_TYPE.BASKETBALL, SPORT_TYPE.FITNESS, SPORT_TYPE.SOCCER, SPORT_TYPE.TABLE_TENNIS];

export {SPORT_TYPE, ALLOWED_SPORT_TYPES}